tam:
- [-0.7071067811848899, -0.7071067811848899, 0.0, 0.0, 0.7071067811868645, 0.7071067811868645]
- [0.7071067811882058, -0.7071067811882058, 0.0, 0.0, 0.7071067811862306, -0.7071067811862306]
- [0.0, 0.0, -1.0000000000000002, -1.0000000000000002, 0.0, 0.0]
- [0.0, 0.0, -0.26988000000000006, 0.26988000000000006, 0.0, 0.0]
- [0.0, 0.0, -0.038280000000203505, 0.03827999999979651, 0.0, 0.0]
- [0.34543580474506674, -0.34543580474506674, 0.0, 0.0, -0.34543580474528773, 0.3454358047452877]